import { Schibsted_Grotesk } from "next/font/google";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "./globals.css";

const schibstedGrotesk = Schibsted_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={schibstedGrotesk.className}>
        <Header />
        <main className="min-h-screen section-container">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
